import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!supabaseUrl || !supabaseServiceKey) {
    console.error('Missing environment variables')
    process.exit(1)
}

const supabase = createClient(supabaseUrl, supabaseServiceKey)

const trendsData = [
    { keyword: 'personalized leather gift', search_volume: 45000, competition: 'High', growth: 125, category: 'Gifts', monthly_searches: [{ "month": "Jan", "volume": 3200 }, { "month": "Feb", "volume": 4100 }, { "month": "Mar", "volume": 3800 }, { "month": "Apr", "volume": 3500 }, { "month": "May", "volume": 3900 }, { "month": "Jun", "volume": 4200 }, { "month": "Jul", "volume": 4500 }, { "month": "Aug", "volume": 4800 }, { "month": "Sep", "volume": 5100 }, { "month": "Oct", "volume": 5500 }, { "month": "Nov", "volume": 6200 }, { "month": "Dec", "volume": 7500 }] },
    { keyword: 'minimalist wall art', search_volume: 28000, competition: 'Medium', growth: 45, category: 'Home Decor', monthly_searches: [{ "month": "Jan", "volume": 2100 }, { "month": "Feb", "volume": 2200 }, { "month": "Mar", "volume": 2300 }, { "month": "Apr", "volume": 2400 }, { "month": "May", "volume": 2300 }, { "month": "Jun", "volume": 2200 }, { "month": "Jul", "volume": 2100 }, { "month": "Aug", "volume": 2300 }, { "month": "Sep", "volume": 2500 }, { "month": "Oct", "volume": 2600 }, { "month": "Nov", "volume": 2800 }, { "month": "Dec", "volume": 2900 }] },
    { keyword: 'vintage denim jacket', search_volume: 12000, competition: 'Low', growth: -15, category: 'Clothing', monthly_searches: [{ "month": "Jan", "volume": 1200 }, { "month": "Feb", "volume": 1100 }, { "month": "Mar", "volume": 1000 }, { "month": "Apr", "volume": 900 }, { "month": "May", "volume": 850 }, { "month": "Jun", "volume": 800 }, { "month": "Jul", "volume": 850 }, { "month": "Aug", "volume": 900 }, { "month": "Sep", "volume": 1100 }, { "month": "Oct", "volume": 1300 }, { "month": "Nov", "volume": 1400 }, { "month": "Dec", "volume": 1500 }] },
    { keyword: 'handmade ceramic mug', search_volume: 18500, competition: 'Medium', growth: 8, category: 'Kitchen', monthly_searches: [{ "month": "Jan", "volume": 1500 }, { "month": "Feb", "volume": 1600 }, { "month": "Mar", "volume": 1550 }, { "month": "Apr", "volume": 1500 }, { "month": "May", "volume": 1450 }, { "month": "Jun", "volume": 1400 }, { "month": "Jul", "volume": 1450 }, { "month": "Aug", "volume": 1500 }, { "month": "Sep", "volume": 1600 }, { "month": "Oct", "volume": 1700 }, { "month": "Nov", "volume": 1800 }, { "month": "Dec", "volume": 2000 }] },
    { keyword: 'digital planner 2025', search_volume: 32000, competition: 'High', growth: 210, category: 'Digital', monthly_searches: [{ "month": "Jan", "volume": 5000 }, { "month": "Feb", "volume": 4000 }, { "month": "Mar", "volume": 3000 }, { "month": "Apr", "volume": 2000 }, { "month": "May", "volume": 1500 }, { "month": "Jun", "volume": 1000 }, { "month": "Jul", "volume": 1200 }, { "month": "Aug", "volume": 1500 }, { "month": "Sep", "volume": 2000 }, { "month": "Oct", "volume": 3000 }, { "month": "Nov", "volume": 5000 }, { "month": "Dec", "volume": 8000 }] },
    { keyword: 'chunky knit blanket', search_volume: 8900, competition: 'Low', growth: -5, category: 'Home Decor', monthly_searches: [{ "month": "Jan", "volume": 1200 }, { "month": "Feb", "volume": 1000 }, { "month": "Mar", "volume": 800 }, { "month": "Apr", "volume": 600 }, { "month": "May", "volume": 500 }, { "month": "Jun", "volume": 400 }, { "month": "Jul", "volume": 450 }, { "month": "Aug", "volume": 600 }, { "month": "Sep", "volume": 800 }, { "month": "Oct", "volume": 1000 }, { "month": "Nov", "volume": 1200 }, { "month": "Dec", "volume": 1500 }] },
    { keyword: 'custom pet portrait', search_volume: 15600, competition: 'Medium', growth: 32, category: 'Art', monthly_searches: [{ "month": "Jan", "volume": 1200 }, { "month": "Feb", "volume": 1300 }, { "month": "Mar", "volume": 1250 }, { "month": "Apr", "volume": 1300 }, { "month": "May", "volume": 1350 }, { "month": "Jun", "volume": 1400 }, { "month": "Jul", "volume": 1450 }, { "month": "Aug", "volume": 1500 }, { "month": "Sep", "volume": 1600 }, { "month": "Oct", "volume": 1700 }, { "month": "Nov", "volume": 2000 }, { "month": "Dec", "volume": 2500 }] },
    { keyword: 'gold hoop earrings', search_volume: 22000, competition: 'High', growth: 15, category: 'Jewelry', monthly_searches: [{ "month": "Jan", "volume": 1800 }, { "month": "Feb", "volume": 1900 }, { "month": "Mar", "volume": 1850 }, { "month": "Apr", "volume": 1800 }, { "month": "May", "volume": 1850 }, { "month": "Jun", "volume": 1900 }, { "month": "Jul", "volume": 2000 }, { "month": "Aug", "volume": 2100 }, { "month": "Sep", "volume": 2000 }, { "month": "Oct", "volume": 1900 }, { "month": "Nov", "volume": 2000 }, { "month": "Dec", "volume": 2200 }] },
    { keyword: 'printable wedding planner', search_volume: 14500, competition: 'Medium', growth: 60, category: 'Weddings', monthly_searches: [{ "month": "Jan", "volume": 2000 }, { "month": "Feb", "volume": 1800 }, { "month": "Mar", "volume": 1600 }, { "month": "Apr", "volume": 1400 }, { "month": "May", "volume": 1200 }, { "month": "Jun", "volume": 1000 }, { "month": "Jul", "volume": 900 }, { "month": "Aug", "volume": 800 }, { "month": "Sep", "volume": 900 }, { "month": "Oct", "volume": 1000 }, { "month": "Nov", "volume": 1500 }, { "month": "Dec", "volume": 2500 }] },
    { keyword: 'soy wax candle', search_volume: 19800, competition: 'Medium', growth: 12, category: 'Home Decor', monthly_searches: [{ "month": "Jan", "volume": 1600 }, { "month": "Feb", "volume": 1500 }, { "month": "Mar", "volume": 1400 }, { "month": "Apr", "volume": 1300 }, { "month": "May", "volume": 1200 }, { "month": "Jun", "volume": 1100 }, { "month": "Jul", "volume": 1200 }, { "month": "Aug", "volume": 1300 }, { "month": "Sep", "volume": 1500 }, { "month": "Oct", "volume": 1800 }, { "month": "Nov", "volume": 2200 }, { "month": "Dec", "volume": 2800 }] },
    { keyword: 'linen dress', search_volume: 25400, competition: 'High', growth: -8, category: 'Clothing', monthly_searches: [{ "month": "Jan", "volume": 1000 }, { "month": "Feb", "volume": 1200 }, { "month": "Mar", "volume": 1500 }, { "month": "Apr", "volume": 2000 }, { "month": "May", "volume": 2500 }, { "month": "Jun", "volume": 3000 }, { "month": "Jul", "volume": 3500 }, { "month": "Aug", "volume": 3000 }, { "month": "Sep", "volume": 2000 }, { "month": "Oct", "volume": 1500 }, { "month": "Nov", "volume": 1000 }, { "month": "Dec", "volume": 800 }] },
    { keyword: 'wooden baby toys', search_volume: 11200, competition: 'Medium', growth: 25, category: 'Toys', monthly_searches: [{ "month": "Jan", "volume": 900 }, { "month": "Feb", "volume": 800 }, { "month": "Mar", "volume": 850 }, { "month": "Apr", "volume": 900 }, { "month": "May", "volume": 950 }, { "month": "Jun", "volume": 1000 }, { "month": "Jul", "volume": 1050 }, { "month": "Aug", "volume": 1100 }, { "month": "Sep", "volume": 1200 }, { "month": "Oct", "volume": 1300 }, { "month": "Nov", "volume": 1500 }, { "month": "Dec", "volume": 1800 }] },
    { keyword: 'macrame plant hanger', search_volume: 9500, competition: 'Low', growth: -2, category: 'Home Decor', monthly_searches: [{ "month": "Jan", "volume": 800 }, { "month": "Feb", "volume": 850 }, { "month": "Mar", "volume": 900 }, { "month": "Apr", "volume": 950 }, { "month": "May", "volume": 1000 }, { "month": "Jun", "volume": 950 }, { "month": "Jul", "volume": 900 }, { "month": "Aug", "volume": 850 }, { "month": "Sep", "volume": 800 }, { "month": "Oct", "volume": 750 }, { "month": "Nov", "volume": 700 }, { "month": "Dec", "volume": 650 }] },
    { keyword: 'crystal necklace', search_volume: 31000, competition: 'High', growth: 18, category: 'Jewelry', monthly_searches: [{ "month": "Jan", "volume": 2500 }, { "month": "Feb", "volume": 2600 }, { "month": "Mar", "volume": 2550 }, { "month": "Apr", "volume": 2500 }, { "month": "May", "volume": 2450 }, { "month": "Jun", "volume": 2400 }, { "month": "Jul", "volume": 2500 }, { "month": "Aug", "volume": 2600 }, { "month": "Sep", "volume": 2700 }, { "month": "Oct", "volume": 2800 }, { "month": "Nov", "volume": 3000 }, { "month": "Dec", "volume": 3200 }] },
    { keyword: 'personalized doormat', search_volume: 16700, competition: 'Medium', growth: 40, category: 'Home Decor', monthly_searches: [{ "month": "Jan", "volume": 1000 }, { "month": "Feb", "volume": 1100 }, { "month": "Mar", "volume": 1200 }, { "month": "Apr", "volume": 1500 }, { "month": "May", "volume": 1800 }, { "month": "Jun", "volume": 2000 }, { "month": "Jul", "volume": 1800 }, { "month": "Aug", "volume": 1600 }, { "month": "Sep", "volume": 1500 }, { "month": "Oct", "volume": 1400 }, { "month": "Nov", "volume": 1200 }, { "month": "Dec", "volume": 1000 }] },
    { keyword: 'bridesmaid proposal box', search_volume: 21000, competition: 'High', growth: 55, category: 'Weddings', monthly_searches: [{ "month": "Jan", "volume": 2500 }, { "month": "Feb", "volume": 2200 }, { "month": "Mar", "volume": 2000 }, { "month": "Apr", "volume": 1800 }, { "month": "May", "volume": 1600 }, { "month": "Jun", "volume": 1500 }, { "month": "Jul", "volume": 1400 }, { "month": "Aug", "volume": 1300 }, { "month": "Sep", "volume": 1400 }, { "month": "Oct", "volume": 1500 }, { "month": "Nov", "volume": 1800 }, { "month": "Dec", "volume": 2800 }] },
    { keyword: 'retro sunglasses', search_volume: 8400, competition: 'Low', growth: -12, category: 'Accessories', monthly_searches: [{ "month": "Jan", "volume": 400 }, { "month": "Feb", "volume": 500 }, { "month": "Mar", "volume": 600 }, { "month": "Apr", "volume": 800 }, { "month": "May", "volume": 1000 }, { "month": "Jun", "volume": 1200 }, { "month": "Jul", "volume": 1400 }, { "month": "Aug", "volume": 1200 }, { "month": "Sep", "volume": 800 }, { "month": "Oct", "volume": 600 }, { "month": "Nov", "volume": 400 }, { "month": "Dec", "volume": 300 }] },
    { keyword: 'leather tote bag', search_volume: 13500, competition: 'Medium', growth: 5, category: 'Accessories', monthly_searches: [{ "month": "Jan", "volume": 1100 }, { "month": "Feb", "volume": 1050 }, { "month": "Mar", "volume": 1100 }, { "month": "Apr", "volume": 1150 }, { "month": "May", "volume": 1200 }, { "month": "Jun", "volume": 1150 }, { "month": "Jul", "volume": 1100 }, { "month": "Aug", "volume": 1150 }, { "month": "Sep", "volume": 1200 }, { "month": "Oct", "volume": 1250 }, { "month": "Nov", "volume": 1300 }, { "month": "Dec", "volume": 1400 }] },
    { keyword: 'abstract printable art', search_volume: 10200, competition: 'Low', growth: 22, category: 'Art', monthly_searches: [{ "month": "Jan", "volume": 800 }, { "month": "Feb", "volume": 850 }, { "month": "Mar", "volume": 900 }, { "month": "Apr", "volume": 850 }, { "month": "May", "volume": 800 }, { "month": "Jun", "volume": 750 }, { "month": "Jul", "volume": 800 }, { "month": "Aug", "volume": 850 }, { "month": "Sep", "volume": 900 }, { "month": "Oct", "volume": 950 }, { "month": "Nov", "volume": 1000 }, { "month": "Dec", "volume": 1100 }] },
    { keyword: 'crochet pattern', search_volume: 29000, competition: 'High', growth: 35, category: 'Craft Supplies', monthly_searches: [{ "month": "Jan", "volume": 3000 }, { "month": "Feb", "volume": 2800 }, { "month": "Mar", "volume": 2600 }, { "month": "Apr", "volume": 2400 }, { "month": "May", "volume": 2200 }, { "month": "Jun", "volume": 2000 }, { "month": "Jul", "volume": 2100 }, { "month": "Aug", "volume": 2200 }, { "month": "Sep", "volume": 2400 }, { "month": "Oct", "volume": 2600 }, { "month": "Nov", "volume": 2800 }, { "month": "Dec", "volume": 3200 }] },
    { keyword: 'wedding favors', search_volume: 42000, competition: 'High', growth: 80, category: 'Weddings', monthly_searches: [{ "month": "Jan", "volume": 3000 }, { "month": "Feb", "volume": 3200 }, { "month": "Mar", "volume": 3500 }, { "month": "Apr", "volume": 4000 }, { "month": "May", "volume": 4500 }, { "month": "Jun", "volume": 5000 }, { "month": "Jul", "volume": 4500 }, { "month": "Aug", "volume": 4000 }, { "month": "Sep", "volume": 3500 }, { "month": "Oct", "volume": 3000 }, { "month": "Nov", "volume": 2500 }, { "month": "Dec", "volume": 2000 }] },
    { keyword: 'custom neon sign', search_volume: 17800, competition: 'Medium', growth: 10, category: 'Home Decor', monthly_searches: [{ "month": "Jan", "volume": 1400 }, { "month": "Feb", "volume": 1350 }, { "month": "Mar", "volume": 1400 }, { "month": "Apr", "volume": 1450 }, { "month": "May", "volume": 1500 }, { "month": "Jun", "volume": 1550 }, { "month": "Jul", "volume": 1600 }, { "month": "Aug", "volume": 1550 }, { "month": "Sep", "volume": 1500 }, { "month": "Oct", "volume": 1450 }, { "month": "Nov", "volume": 1400 }, { "month": "Dec", "volume": 1350 }] },
    { keyword: 'beaded bracelet', search_volume: 15200, competition: 'Medium', growth: -5, category: 'Jewelry', monthly_searches: [{ "month": "Jan", "volume": 1300 }, { "month": "Feb", "volume": 1250 }, { "month": "Mar", "volume": 1200 }, { "month": "Apr", "volume": 1150 }, { "month": "May", "volume": 1100 }, { "month": "Jun", "volume": 1200 }, { "month": "Jul", "volume": 1300 }, { "month": "Aug", "volume": 1400 }, { "month": "Sep", "volume": 1300 }, { "month": "Oct", "volume": 1200 }, { "month": "Nov", "volume": 1100 }, { "month": "Dec", "volume": 1000 }] },
    { keyword: 'velvet throw pillow', search_volume: 7600, competition: 'Low', growth: 15, category: 'Home Decor', monthly_searches: [{ "month": "Jan", "volume": 700 }, { "month": "Feb", "volume": 650 }, { "month": "Mar", "volume": 600 }, { "month": "Apr", "volume": 550 }, { "month": "May", "volume": 500 }, { "month": "Jun", "volume": 450 }, { "month": "Jul", "volume": 500 }, { "month": "Aug", "volume": 550 }, { "month": "Sep", "volume": 600 }, { "month": "Oct", "volume": 700 }, { "month": "Nov", "volume": 800 }, { "month": "Dec", "volume": 900 }] },
    { keyword: 'dried flower bouquet', search_volume: 12400, competition: 'Medium', growth: 28, category: 'Home Decor', monthly_searches: [{ "month": "Jan", "volume": 900 }, { "month": "Feb", "volume": 1000 }, { "month": "Mar", "volume": 1100 }, { "month": "Apr", "volume": 1200 }, { "month": "May", "volume": 1300 }, { "month": "Jun", "volume": 1200 }, { "month": "Jul", "volume": 1100 }, { "month": "Aug", "volume": 1000 }, { "month": "Sep", "volume": 900 }, { "month": "Oct", "volume": 950 }, { "month": "Nov", "volume": 1000 }, { "month": "Dec", "volume": 1100 }] },
    { keyword: 'mushroom lamp', search_volume: 6500, competition: 'Low', growth: -20, category: 'Home Decor', monthly_searches: [{ "month": "Jan", "volume": 800 }, { "month": "Feb", "volume": 700 }, { "month": "Mar", "volume": 600 }, { "month": "Apr", "volume": 500 }, { "month": "May", "volume": 400 }, { "month": "Jun", "volume": 350 }, { "month": "Jul", "volume": 400 }, { "month": "Aug", "volume": 450 }, { "month": "Sep", "volume": 500 }, { "month": "Oct", "volume": 550 }, { "month": "Nov", "volume": 600 }, { "month": "Dec", "volume": 650 }] },
    { keyword: 'personalized cutting board', search_volume: 19500, competition: 'Medium', growth: 45, category: 'Kitchen', monthly_searches: [{ "month": "Jan", "volume": 1200 }, { "month": "Feb", "volume": 1100 }, { "month": "Mar", "volume": 1200 }, { "month": "Apr", "volume": 1300 }, { "month": "May", "volume": 1500 }, { "month": "Jun", "volume": 1800 }, { "month": "Jul", "volume": 1600 }, { "month": "Aug", "volume": 1400 }, { "month": "Sep", "volume": 1300 }, { "month": "Oct", "volume": 1500 }, { "month": "Nov", "volume": 2000 }, { "month": "Dec", "volume": 3000 }] },
    { keyword: 'silver ring set', search_volume: 14800, competition: 'Medium', growth: 8, category: 'Jewelry', monthly_searches: [{ "month": "Jan", "volume": 1200 }, { "month": "Feb", "volume": 1250 }, { "month": "Mar", "volume": 1200 }, { "month": "Apr", "volume": 1150 }, { "month": "May", "volume": 1200 }, { "month": "Jun", "volume": 1250 }, { "month": "Jul", "volume": 1300 }, { "month": "Aug", "volume": 1350 }, { "month": "Sep", "volume": 1300 }, { "month": "Oct", "volume": 1250 }, { "month": "Nov", "volume": 1200 }, { "month": "Dec", "volume": 1150 }] },
    { keyword: 'embroidery kit', search_volume: 11500, competition: 'Low', growth: 30, category: 'Craft Supplies', monthly_searches: [{ "month": "Jan", "volume": 1500 }, { "month": "Feb", "volume": 1400 }, { "month": "Mar", "volume": 1300 }, { "month": "Apr", "volume": 1200 }, { "month": "May", "volume": 1100 }, { "month": "Jun", "volume": 1000 }, { "month": "Jul", "volume": 900 }, { "month": "Aug", "volume": 800 }, { "month": "Sep", "volume": 900 }, { "month": "Oct", "volume": 1000 }, { "month": "Nov", "volume": 1200 }, { "month": "Dec", "volume": 1400 }] },
    { keyword: 'wicker storage basket', search_volume: 9800, competition: 'Low', growth: 12, category: 'Home Decor', monthly_searches: [{ "month": "Jan", "volume": 1000 }, { "month": "Feb", "volume": 950 }, { "month": "Mar", "volume": 900 }, { "month": "Apr", "volume": 850 }, { "month": "May", "volume": 800 }, { "month": "Jun", "volume": 750 }, { "month": "Jul", "volume": 800 }, { "month": "Aug", "volume": 850 }, { "month": "Sep", "volume": 900 }, { "month": "Oct", "volume": 950 }, { "month": "Nov", "volume": 1000 }, { "month": "Dec", "volume": 1100 }] },
    { keyword: 'silk scarf', search_volume: 8200, competition: 'Low', growth: -3, category: 'Accessories', monthly_searches: [{ "month": "Jan", "volume": 600 }, { "month": "Feb", "volume": 650 }, { "month": "Mar", "volume": 700 }, { "month": "Apr", "volume": 750 }, { "month": "May", "volume": 800 }, { "month": "Jun", "volume": 750 }, { "month": "Jul", "volume": 700 }, { "month": "Aug", "volume": 650 }, { "month": "Sep", "volume": 600 }, { "month": "Oct", "volume": 650 }, { "month": "Nov", "volume": 700 }, { "month": "Dec", "volume": 750 }] },
    { keyword: 'ceramic vase', search_volume: 13100, competition: 'Medium', growth: 18, category: 'Home Decor', monthly_searches: [{ "month": "Jan", "volume": 1000 }, { "month": "Feb", "volume": 1050 }, { "month": "Mar", "volume": 1100 }, { "month": "Apr", "volume": 1150 }, { "month": "May", "volume": 1200 }, { "month": "Jun", "volume": 1150 }, { "month": "Jul", "volume": 1100 }, { "month": "Aug", "volume": 1050 }, { "month": "Sep", "volume": 1000 }, { "month": "Oct", "volume": 1050 }, { "month": "Nov", "volume": 1100 }, { "month": "Dec", "volume": 1150 }] },
    { keyword: 'leather wallet', search_volume: 20500, competition: 'Medium', growth: 6, category: 'Accessories', monthly_searches: [{ "month": "Jan", "volume": 1500 }, { "month": "Feb", "volume": 1400 }, { "month": "Mar", "volume": 1500 }, { "month": "Apr", "volume": 1600 }, { "month": "May", "volume": 1700 }, { "month": "Jun", "volume": 1800 }, { "month": "Jul", "volume": 1700 }, { "month": "Aug", "volume": 1600 }, { "month": "Sep", "volume": 1500 }, { "month": "Oct", "volume": 1600 }, { "month": "Nov", "volume": 1800 }, { "month": "Dec", "volume": 2200 }] },
    { keyword: 'baby shower gift', search_volume: 35000, competition: 'High', growth: 50, category: 'Gifts', monthly_searches: [{ "month": "Jan", "volume": 2500 }, { "month": "Feb", "volume": 2600 }, { "month": "Mar", "volume": 2800 }, { "month": "Apr", "volume": 3000 }, { "month": "May", "volume": 3200 }, { "month": "Jun", "volume": 3500 }, { "month": "Jul", "volume": 3200 }, { "month": "Aug", "volume": 3000 }, { "month": "Sep", "volume": 2800 }, { "month": "Oct", "volume": 2600 }, { "month": "Nov", "volume": 2500 }, { "month": "Dec", "volume": 2400 }] },
    { keyword: 'dog collar', search_volume: 16200, competition: 'Medium', growth: 10, category: 'Pets', monthly_searches: [{ "month": "Jan", "volume": 1200 }, { "month": "Feb", "volume": 1250 }, { "month": "Mar", "volume": 1300 }, { "month": "Apr", "volume": 1350 }, { "month": "May", "volume": 1400 }, { "month": "Jun", "volume": 1450 }, { "month": "Jul", "volume": 1500 }, { "month": "Aug", "volume": 1450 }, { "month": "Sep", "volume": 1400 }, { "month": "Oct", "volume": 1350 }, { "month": "Nov", "volume": 1300 }, { "month": "Dec", "volume": 1250 }] },
    { keyword: 'planner stickers', search_volume: 24000, competition: 'Medium', growth: 25, category: 'Stationery', monthly_searches: [{ "month": "Jan", "volume": 3000 }, { "month": "Feb", "volume": 2500 }, { "month": "Mar", "volume": 2000 }, { "month": "Apr", "volume": 1800 }, { "month": "May", "volume": 1600 }, { "month": "Jun", "volume": 1500 }, { "month": "Jul", "volume": 1600 }, { "month": "Aug", "volume": 1800 }, { "month": "Sep", "volume": 2000 }, { "month": "Oct", "volume": 2200 }, { "month": "Nov", "volume": 2500 }, { "month": "Dec", "volume": 2800 }] },
    { keyword: 'wall hanging', search_volume: 10800, competition: 'Low', growth: -8, category: 'Home Decor', monthly_searches: [{ "month": "Jan", "volume": 1000 }, { "month": "Feb", "volume": 950 }, { "month": "Mar", "volume": 900 }, { "month": "Apr", "volume": 850 }, { "month": "May", "volume": 800 }, { "month": "Jun", "volume": 750 }, { "month": "Jul", "volume": 800 }, { "month": "Aug", "volume": 850 }, { "month": "Sep", "volume": 900 }, { "month": "Oct", "volume": 950 }, { "month": "Nov", "volume": 1000 }, { "month": "Dec", "volume": 1050 }] },
    { keyword: 'scented soap', search_volume: 7900, competition: 'Low', growth: 15, category: 'Bath & Beauty', monthly_searches: [{ "month": "Jan", "volume": 600 }, { "month": "Feb", "volume": 650 }, { "month": "Mar", "volume": 700 }, { "month": "Apr", "volume": 650 }, { "month": "May", "volume": 600 }, { "month": "Jun", "volume": 550 }, { "month": "Jul", "volume": 600 }, { "month": "Aug", "volume": 650 }, { "month": "Sep", "volume": 700 }, { "month": "Oct", "volume": 750 }, { "month": "Nov", "volume": 800 }, { "month": "Dec", "volume": 900 }] },
    { keyword: 'custom t-shirt', search_volume: 48000, competition: 'High', growth: 65, category: 'Clothing', monthly_searches: [{ "month": "Jan", "volume": 3000 }, { "month": "Feb", "volume": 3200 }, { "month": "Mar", "volume": 3500 }, { "month": "Apr", "volume": 4000 }, { "month": "May", "volume": 4500 }, { "month": "Jun", "volume": 5000 }, { "month": "Jul", "volume": 5500 }, { "month": "Aug", "volume": 5000 }, { "month": "Sep", "volume": 4500 }, { "month": "Oct", "volume": 4000 }, { "month": "Nov", "volume": 3500 }, { "month": "Dec", "volume": 3000 }] },
    { keyword: 'digital invitation', search_volume: 22500, competition: 'Medium', growth: 90, category: 'Digital', monthly_searches: [{ "month": "Jan", "volume": 2000 }, { "month": "Feb", "volume": 1800 }, { "month": "Mar", "volume": 1600 }, { "month": "Apr", "volume": 1500 }, { "month": "May", "volume": 1800 }, { "month": "Jun", "volume": 2000 }, { "month": "Jul", "volume": 1800 }, { "month": "Aug", "volume": 1600 }, { "month": "Sep", "volume": 1500 }, { "month": "Oct", "volume": 1400 }, { "month": "Nov", "volume": 1200 }, { "month": "Dec", "volume": 1000 }] },
    { keyword: 'wooden puzzle', search_volume: 11800, competition: 'Medium', growth: 20, category: 'Toys', monthly_searches: [{ "month": "Jan", "volume": 1200 }, { "month": "Feb", "volume": 1000 }, { "month": "Mar", "volume": 900 }, { "month": "Apr", "volume": 800 }, { "month": "May", "volume": 700 }, { "month": "Jun", "volume": 600 }, { "month": "Jul", "volume": 700 }, { "month": "Aug", "volume": 800 }, { "month": "Sep", "volume": 900 }, { "month": "Oct", "volume": 1000 }, { "month": "Nov", "volume": 1200 }, { "month": "Dec", "volume": 1500 }] },
    { keyword: 'gold necklace', search_volume: 27000, competition: 'High', growth: 12, category: 'Jewelry', monthly_searches: [{ "month": "Jan", "volume": 2000 }, { "month": "Feb", "volume": 2200 }, { "month": "Mar", "volume": 2100 }, { "month": "Apr", "volume": 2000 }, { "month": "May", "volume": 2100 }, { "month": "Jun", "volume": 2200 }, { "month": "Jul", "volume": 2300 }, { "month": "Aug", "volume": 2400 }, { "month": "Sep", "volume": 2300 }, { "month": "Oct", "volume": 2200 }, { "month": "Nov", "volume": 2300 }, { "month": "Dec", "volume": 2500 }] },
    { keyword: 'canvas tote bag', search_volume: 14200, competition: 'Medium', growth: 35, category: 'Accessories', monthly_searches: [{ "month": "Jan", "volume": 1000 }, { "month": "Feb", "volume": 1100 }, { "month": "Mar", "volume": 1200 }, { "month": "Apr", "volume": 1300 }, { "month": "May", "volume": 1400 }, { "month": "Jun", "volume": 1500 }, { "month": "Jul", "volume": 1400 }, { "month": "Aug", "volume": 1300 }, { "month": "Sep", "volume": 1200 }, { "month": "Oct", "volume": 1100 }, { "month": "Nov", "volume": 1000 }, { "month": "Dec", "volume": 900 }] },
    { keyword: 'hair clips', search_volume: 18500, competition: 'Medium', growth: 40, category: 'Accessories', monthly_searches: [{ "month": "Jan", "volume": 1200 }, { "month": "Feb", "volume": 1300 }, { "month": "Mar", "volume": 1400 }, { "month": "Apr", "volume": 1500 }, { "month": "May", "volume": 1600 }, { "month": "Jun", "volume": 1700 }, { "month": "Jul", "volume": 1800 }, { "month": "Aug", "volume": 1700 }, { "month": "Sep", "volume": 1600 }, { "month": "Oct", "volume": 1500 }, { "month": "Nov", "volume": 1400 }, { "month": "Dec", "volume": 1300 }] },
    { keyword: 'bath bombs', search_volume: 15600, competition: 'Medium', growth: 5, category: 'Bath & Beauty', monthly_searches: [{ "month": "Jan", "volume": 1500 }, { "month": "Feb", "volume": 1400 }, { "month": "Mar", "volume": 1300 }, { "month": "Apr", "volume": 1200 }, { "month": "May", "volume": 1100 }, { "month": "Jun", "volume": 1000 }, { "month": "Jul", "volume": 1100 }, { "month": "Aug", "volume": 1200 }, { "month": "Sep", "volume": 1300 }, { "month": "Oct", "volume": 1400 }, { "month": "Nov", "volume": 1500 }, { "month": "Dec", "volume": 1600 }] },
    { keyword: 'phone case', search_volume: 38000, competition: 'High', growth: 15, category: 'Accessories', monthly_searches: [{ "month": "Jan", "volume": 3000 }, { "month": "Feb", "volume": 3100 }, { "month": "Mar", "volume": 3200 }, { "month": "Apr", "volume": 3300 }, { "month": "May", "volume": 3200 }, { "month": "Jun", "volume": 3100 }, { "month": "Jul", "volume": 3200 }, { "month": "Aug", "volume": 3300 }, { "month": "Sep", "volume": 3400 }, { "month": "Oct", "volume": 3500 }, { "month": "Nov", "volume": 3600 }, { "month": "Dec", "volume": 3800 }] },
    { keyword: 'laptop sticker', search_volume: 21500, competition: 'Medium', growth: 28, category: 'Stationery', monthly_searches: [{ "month": "Jan", "volume": 1500 }, { "month": "Feb", "volume": 1600 }, { "month": "Mar", "volume": 1700 }, { "month": "Apr", "volume": 1800 }, { "month": "May", "volume": 1900 }, { "month": "Jun", "volume": 2000 }, { "month": "Jul", "volume": 2100 }, { "month": "Aug", "volume": 2000 }, { "month": "Sep", "volume": 1900 }, { "month": "Oct", "volume": 1800 }, { "month": "Nov", "volume": 1700 }, { "month": "Dec", "volume": 1600 }] },
    { keyword: 'keychain', search_volume: 12900, competition: 'Low', growth: 10, category: 'Accessories', monthly_searches: [{ "month": "Jan", "volume": 1000 }, { "month": "Feb", "volume": 1050 }, { "month": "Mar", "volume": 1100 }, { "month": "Apr", "volume": 1050 }, { "month": "May", "volume": 1000 }, { "month": "Jun", "volume": 1050 }, { "month": "Jul", "volume": 1100 }, { "month": "Aug", "volume": 1150 }, { "month": "Sep", "volume": 1200 }, { "month": "Oct", "volume": 1250 }, { "month": "Nov", "volume": 1300 }, { "month": "Dec", "volume": 1350 }] },
    { keyword: 'poster print', search_volume: 9400, competition: 'Low', growth: -5, category: 'Art', monthly_searches: [{ "month": "Jan", "volume": 800 }, { "month": "Feb", "volume": 850 }, { "month": "Mar", "volume": 800 }, { "month": "Apr", "volume": 750 }, { "month": "May", "volume": 700 }, { "month": "Jun", "volume": 750 }, { "month": "Jul", "volume": 800 }, { "month": "Aug", "volume": 850 }, { "month": "Sep", "volume": 900 }, { "month": "Oct", "volume": 950 }, { "month": "Nov", "volume": 1000 }, { "month": "Dec", "volume": 1050 }] },
    { keyword: 'desk organizer', search_volume: 16800, competition: 'Medium', growth: 45, category: 'Office', monthly_searches: [{ "month": "Jan", "volume": 2000 }, { "month": "Feb", "volume": 1800 }, { "month": "Mar", "volume": 1600 }, { "month": "Apr", "volume": 1400 }, { "month": "May", "volume": 1200 }, { "month": "Jun", "volume": 1000 }, { "month": "Jul", "volume": 1200 }, { "month": "Aug", "volume": 1400 }, { "month": "Sep", "volume": 1600 }, { "month": "Oct", "volume": 1800 }, { "month": "Nov", "volume": 2000 }, { "month": "Dec", "volume": 2200 }] },
    { keyword: 'yoga mat strap', search_volume: 5200, competition: 'Low', growth: 12, category: 'Fitness', monthly_searches: [{ "month": "Jan", "volume": 400 }, { "month": "Feb", "volume": 450 }, { "month": "Mar", "volume": 500 }, { "month": "Apr", "volume": 450 }, { "month": "May", "volume": 400 }, { "month": "Jun", "volume": 350 }, { "month": "Jul", "volume": 400 }, { "month": "Aug", "volume": 450 }, { "month": "Sep", "volume": 500 }, { "month": "Oct", "volume": 550 }, { "month": "Nov", "volume": 600 }, { "month": "Dec", "volume": 650 }] },
    { keyword: 'travel journal', search_volume: 8700, competition: 'Low', growth: 30, category: 'Stationery', monthly_searches: [{ "month": "Jan", "volume": 800 }, { "month": "Feb", "volume": 700 }, { "month": "Mar", "volume": 600 }, { "month": "Apr", "volume": 700 }, { "month": "May", "volume": 800 }, { "month": "Jun", "volume": 900 }, { "month": "Jul", "volume": 1000 }, { "month": "Aug", "volume": 900 }, { "month": "Sep", "volume": 800 }, { "month": "Oct", "volume": 700 }, { "month": "Nov", "volume": 600 }, { "month": "Dec", "volume": 500 }] }
]

async function seed() {
    console.log('Seeding trends...')

    // Clear existing data? Maybe not, just insert.
    // But to avoid duplicates if we run multiple times, maybe we should clear first?
    // User said "database seems empty", so I'll assume it's empty.

    const { error } = await supabase.from('trends').insert(trendsData)

    if (error) {
        console.error('Error seeding trends:', error)
        process.exit(1)
    } else {
        console.log('Successfully seeded trends!')
    }
}

seed()
